apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetimesecret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onetimesecret
  template:
    metadata:
      labels:
        app: onetimesecret
    spec:
      containers:
      - name: onetimesecret
        image: dismantl/onetimesecret:latest
        ports:
        - containerPort: 7143
        volumeMounts:
          - name: config-volume
            mountPath: /etc/onetime/config
          - name: redis-volume
            mountPath: /var/run/redis
        env:
            - name: OTS_NAME
              value: "John Doe"
            - name: OTS_SECRET
              value: "f8e1c604d5cf6ff9281d8814ab01ea7385f1364a"
      volumes:
            - name: config-volume
              emptyDir: { }  # Use a PersistentVolumeClaim for real persistence
            - name: redis-volume
              emptyDir: { }  # Use a PersistentVolumeClaim for real persistence



---
apiVersion: v1
kind: Service
metadata:
  name: onetimesecret
spec:
  selector:
    app: onetimesecret
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7143
