apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetimesecret
spec:
  replicas: 2
  selector:
    matchLabels:
      app: onetimesecret
  template:
    metadata:
      labels:
        app: onetimesecret
    spec:
      containers:
      - name: onetimesecret
        image: dismantl/onetimesecret:latest
        ports:
        - containerPort: 7143
        env:
          - name: RafaelViola
            value: "your_secret_value"
          - name: DATABASE_URL
            value: "postgres://user:password@hostname/dbname"

---
apiVersion: v1
kind: Service
metadata:
  name: onetimesecret
spec:
  selector:
    app: onetimesecret
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7143
