apiVersion: apps/v1
kind: Deployment
metadata:
  name: onetimesecret
spec:
  replicas: 1
  selector:
    matchLabels:
      app: onetimesecret
  template:
    metadata:
      labels:
        app: onetimesecret
    spec:
      containers:
      - name: onetimesecret
        image: dismantl/onetimesecret:latest
        ports:
        - containerPort: 7143
        volumeMounts:
          - name: config-volume
            mountPath: /etc/onetime/config
            subPath: config
        env:
            - name: HOST
              value: ":80"
            - name: SECRET
              value: "CHANGEME"
            - name: REDIS_URL
              value: "redis-11858.c11.us-east-1-3.ec2.redns.redis-cloud.com:11858"
            - name: viola
              value: "rafaelmachadoviola@enta.pt"
      volumes:
            - name: config-volume
              configMap:
                name: onetimesecret


---
apiVersion: v1
kind: Service
metadata:
  name: onetimesecret
spec:
  selector:
    app: onetimesecret
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7143

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: onetimesecret
data:
  config: |
    :site:
      :host: <%= ENV['HOST'] || 'localhost:3000' %>
      :domain: localhost
      :ssl: <%= ENV['SSL'] == 'true' %>
      :secret: <%= ENV['SECRET'] || 'CHANGEME' %>
    :redis:
      :uri: <%= ENV['REDIS_URL'] || 'redis://CHANGEME@127.0.0.1:6379/0' %>
    :colonels:
      - <%= ENV['viola'] || 'rafaelmachadoviola@enta.pt' %>
    :emailer:
      :mode: :smtp
      :from: CHANGEME@example.com
      :fromname: Jan
      :host: localhost
      :port: 587
      :tls: true
      :user:
      :pass:
    :locales:
      - ru
      - en
      - ar
      - bg
      - ca_ES
      - cn
      - cs
      - da_DK
      - de
      - el_GR
      - en
      - es
      - fr
      - fr_FR
      - he
      - hu
      - it_IT
      - nl
      - pl
      - pt_BR
      - sl_SI
      - sv_SE
      - tr
      - vi
    :limits:
      :create_secret: 1000
      :create_account: 10
      :update_account: 10
      :email_recipient: 50
      :send_feedback: 10
      :authenticate_session: 5
      :homepage: 1000
      :dashboard: 1000
      :failed_passphrase: 5
      :show_metadata: 1000
      :show_secret: 1000
      :burn_secret: 1000
